---
title: "R Notebook"
output: git
editor_options: 
  chunk_output_type: inline
---
```{r}
library(statsr)
library(MASS)
library(dplyr)
library(ggplot2)
library(BAS)
library(ggcorrplot)
```


```{r}
data(wage)
wagos <- wage %>% select(-c(married,black,south,urban,lwage)) %>% na.omit()

corr <- round(cor(wagos),3)
ggcorrplot(corr, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="circle", 
           colors = c("tomato2", "white", "springgreen3"), 
           title="Correlogram of Wages", 
           ggtheme=theme_bw)
```

```{r}
ggplot(wagos,aes(x=kww,y=wage,group=kww)) + geom_boxplot()
ggplot(wagos,aes(x=educ,y=wage,group=educ)) + geom_boxplot()
ggplot(wagos,aes(x=iq,y=wage,group=iq)) + geom_point()
```
```{r}
m_wage_iq = lm(wage ~ iq, data = wage)
m_wage_iq$coefficients
hist(residuals(m_wage_iq),breaks = 50)
qqplot(wage$wage,residuals(m_wage_iq))
```
```{r}
m_wage_educ = lm(wage ~ educ, data = wage)
m_wage_educ$coefficients
hist(residuals(m_wage_educ),breaks = 50)
qqplot(wage$wage,residuals(m_wage_educ))
```
```{r}
m_lwage_iq = lm(lwage ~ iq, data = wage)
m_lwage_iq$coefficients
hist(residuals(m_lwage_iq),breaks = 50)
qqplot(wage$lwage,residuals(m_lwage_iq))
```
```{r}
m_lwage_iq = lm(lwage ~ iq, data = wage)
out = summary(m_lwage_iq)$coef[, 1:2]
out
out = cbind(out, confint(m_lwage_iq))
colnames(out) = c("posterior mean", "sd", "2.5", "97.5")
#round(out, 2)
out

```

```{r}
wage_clean<-wage %>% na.omit()
dim(wage_clean)
m_lwage_full = lm(lwage ~ . - wage, data = wage_clean)
summary(m_lwage_full)
```

```{r}
BIC(m_lwage_full)
```

```{r}
m_lwage_nobrthord = lm(lwage ~ . -wage -brthord, data = na.omit(wage))
BIC(m_lwage_nobrthord)
```

```{r}
m_lwage_nosibs = lm(lwage ~ . -wage -sibs, data = na.omit(wage))
BIC(m_lwage_nosibs)
```

```{r}
m_lwage_nofeduc = lm(lwage ~ . -wage -feduc, data = na.omit(wage))
BIC(m_lwage_nofeduc)
```

```{r}
m_lwage_nomeduc = lm(lwage ~ . -wage -meduc, data = na.omit(wage))
BIC(m_lwage_nomeduc)
```

```{r}
stepAIC(m_lwage_full,k = log(937))
```
```{r}
wage_no_na = na.omit(wage)
bma_lwage = bas.lm(lwage ~ . -wage, data = wage_no_na,
                   prior = "BIC", 
                   modelprior = uniform())
bma_lwage
```
```{r}
wage_red = wage %>%
  select(-sibs, -brthord, -meduc, -feduc)

bma_lwage_red = bas.lm(lwage ~ . -wage, data = wage_red,
                   prior = "BIC", 
                   modelprior = uniform())
bma_lwage_red
summary(bma_lwage_red)


```

```{r}
set.seed(314)
N = 100000
phi = rgamma(N,2,2)
sigma2 = 1/phi
mu = rnorm(N, 1, sqrt(sigma2/4))
y_5 = rnorm(N, mu, sqrt(sigma2))


error <-qnorm(0.975) *sigma2/sqrt(N)
mean(y_5)
mean(y_5) +error
mean(y_5) -error


```

```{r}

data(bodyfat)
summary(bodyfat)
```

```{r}
bodyfat.lm = lm(Bodyfat ~ Abdomen, data=bodyfat)
summary(bodyfat.lm)
x = bodyfat$Abdomen
y= bodyfat$Bodyfat


xnew <- seq(min(x), max(x), length.out = 100)
ynew <- data.frame(predict(bodyfat.lm, newdata = data.frame(Abdomen = xnew),
interval = "confidence", level = 0.95))

plot(x,y, xlab = "abdomen", ylab="bodyfat", col="blue", pch=16)
lines(ynew$lwr ~ xnew, lty = 2, lwd=3, col="cyan")
lines(ynew$upr ~ xnew, lty = 2, lwd=3, col="cyan")




abline(bodyfat.lm, col="orange")

ynew <- data.frame(predict(bodyfat.lm, newdata = data.frame(Abdomen = xnew),
interval = "prediction", level = 0.95))

lines(ynew$lwr ~ xnew, lty = 3, lwd=3, col="red")
lines(ynew$upr ~ xnew, lty = 3, lwd=3, col="red")
points(bodyfat[39,"Abdomen"], bodyfat[39,"Bodyfat"], col="orange", cex=5)
legend(110,15, legend=c("Posterior mean", "95% CI for mean", "95% CI for predictions"),
col=c("orange",rep("grey", 2)), lwd=3, lty=c(1,2, 3))
```

```{r}
predict(bodyfat.lm, newdata=bodyfat[39,], interval="prediction", level=.095)
```

